name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Determine Deployment Environment
        id: set-env
        run: |
          if [[ "${{ github.event.workflow_run.outputs.base_ref }}" == "QA" ]]; then
            echo "environment=QA" >> $GITHUB_ENV
            echo "hosts=${{ secrets.EC2_HOSTSQA }}" >> $GITHUB_ENV
            echo "key=${{ secrets.EC2_KEYQA }}" >> $GITHUB_ENV
            echo "tag=qa" >> $GITHUB_ENV
          elif [[ "${{ github.event.workflow_run.outputs.base_ref }}" == "main" ]]; then
            echo "environment=Production" >> $GITHUB_ENV
            echo "hosts=${{ secrets.EC2_HOSTPROD }}" >> $GITHUB_ENV
            echo "key=${{ secrets.EC2_KEY }}" >> $GITHUB_ENV
            echo "tag=prod" >> $GITHUB_ENV
          else
            echo "Unknown branch, skipping deployment."
            exit 1
          fi

      - name: Deploy to EC2 Instances
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.hosts }}
          username: ubuntu
          key: ${{ env.key }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/lb_asg:${{ env.tag }}
            sudo docker stop $(docker ps -q) || true
            sudo docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/lb_asg:${{ env.tag }}