name: CI Pipeline

on:
  pull_request:
    branches:
      - "QA"
      - "main"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t ${{secrets.DOCKER_USERNAME}}/lb_asg
    - name: Push to Dockerhub
      run: docker push ${{secrets.DOCKER_USERNAME}}/lb_asg:latest