name: CI Pipeline

on:
  pull_request:
    branches:
      - "QA"
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build and Tag the Docker Image
        run: |
          if [[ "${{github.base_ref}}" == "QA" ]]; then
            docker build -t ${{secrets.DOCKER_USERNAME}}/lb_asg:qa .
          elif [[ "${{github.base_ref}}" == "main" ]]; then
            docker build -t ${{secrets.DOCKER_USERNAME}}/lb_asg:prod .
          fi

      - name: Push the Docker Image
        run: |
          if [[ "${{github.base_ref}}" == "QA" ]]; then
            docker push ${{secrets.DOCKER_USERNAME}}/lb_asg:qa
          elif [[ "${{github.base_ref}}" == "main" ]]; then
            docker push ${{secrets.DOCKER_USERNAME}}/lb_asg:prod
          fi